name: hello-world
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
  job2:
     runs-on: ubuntu-latest
     needs: job1
     steps:
       - name: my-step
         run: echo "Hello Don!"
  job3:
     runs-on: ubuntu-latest
     needs: job1
     steps:
       - name: my-step
         run: echo "Hello Man!"
        
    
    
    
