name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name: my-step
        run: echo "Hello Anna!"
      - name: my-step
        run: echo "Hello Karan!"
        
    
    
    
