name: docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Change directory to notebook location
      run: cd path/to/notebook/directory

    - name: Run Jupyter Notebook conversion
      run: jupyter nbconvert --to script docker.ipynb

    - name: Run Python script and capture output
      run: python docker.py > result.txt

    - name: Print ML results
      run: cat result.txt
