# .github/workflows/push-to-docker.yml

name: Push to Docker Hub

on:
  push:
    branches:
      - main  # Adjust this according to your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t karantak/docker-notebook .
          docker push karantak/docker-notebook
