name: ML Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt  # Modify based on your project's requirements

    - name: Run ML script
      run: |
        python githubActionsBasic.py > ml_results.txt
        echo "::set-output name=mse::$(grep 'Mean Squared Error:' ml_results.txt | cut -d ':' -f 2 | xargs)"
        echo "::set-output name=r2::$(grep 'R2 Score:' ml_results.txt | cut -d ':' -f 2 | xargs)"

    - name: Print ML results
      run: cat ml_results.txt  # Replace with the actual output file from your ML script

  print-results:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Print metrics
      run: |
        echo "Mean Squared Error: ${{ needs.build.outputs.mse }}"
        echo "R2 Score: ${{ needs.build.outputs.r2 }}"
