name: ml-workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@latest
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install jupyter
        pip install numpy as np # Add any other dependencies your notebook requires
        pip install scikit-learn 
        pip install matplotlib

    - name: Run Jupyter Notebook conversion
      run: jupyter nbconvert --to script githubActionsBasic.ipynb

    - name: Run Python script and capture output
      run: python githubActionsBasic.py > ml_results.txt

    - name: Print ML results
      run: cat ml_results.txt
