name: ML Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Run ML script
      run: python githubActionsBasic.py > ml_results.txt

    - name: Print ML results
      run: cat ml_results.txt
