name: sequential-workflow

on:
  workflow_dispatch:

jobs:
  preprocessing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install jupyter
        pip install numpy
        pip install scikit-learn
        # Add other dependencies

    - name: Convert notebook to script
      run: jupyter nbconvert --to script github_actions_sequential_run.ipynb

    - name: Run Preprocessing
      run: python github_actions_sequential_run.py preprocessing > output.log

    - name: Saving training file
      uses: actions/upload-artifact@v2
      with:
        name: train-array
        path: train_array.npy
        
    - name: Saving testing file
      uses: actions/upload-artifact@v2
      with:
        name: test-array
        path: test_array.npy   
        
    - name: Print Preprocessing Output
      run: echo "Preprocessing Output:" && cat output.log

  model_building:
    runs-on: ubuntu-latest
    needs: preprocessing

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install jupyter
        pip install numpy
        pip install scikit-learn
        # Add other dependencies

    - name: Convert notebook to script
      run: jupyter nbconvert --to script github_actions_sequential_run.ipynb

    - name: Loading training file
      uses: actions/download-artifact@v2
      with:
        name: train-array
        
    - name: Run Model Building
      run: python github_actions_sequential_run.py model_building > output.log
      
    - name: Saving model
      uses: actions/upload-artifact@v2
      with:
        name: model-pkl 
        path: model.pkl      

    - name: Print Model Building Output
      run: echo "Model Building Output:" && cat output.log

  model_evaluation:
    runs-on: ubuntu-latest
    needs: model_building

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install jupyter
        pip install numpy
        pip install scikit-learn
        # Add other dependencies

    - name: Loading test file
      uses: actions/download-artifact@v2
      with:
        name: test-array        

    - name: Loading model
      uses: actions/download-artifact@v2
      with:
        name: model-pkl       

    - name: Convert notebook to script
      run: jupyter nbconvert --to script github_actions_sequential_run.ipynb

    - name: Run Model Evaluation
      run: python github_actions_sequential_run.py model_evaluation > output.log

    - name: Print Model Evaluation Output
      run: echo "Model Evaluation Output:" && cat output.log
